name: Java CI with Maven

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches:
      - master

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 11
          cache: maven

      - name: Test with Maven
        run: mvn test -B -ntp

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./target/surefire-reports

  deploy:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 11
          cache: maven
          server-id: github
          server-username: GITHUB_USER
          server-password: GITHUB_TOKEN

      - name: Release Maven package
        run: mvn -P release -B -ntp deploy -DskipTests
        env:
          GITHUB_USER: backpaper0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

