name: Java CI with Maven

on:
  push:
    branches: 
    - master
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'pom.xml'
  pull_request:
    branches:
    - master

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Test with Maven
      run: mvn test -B

    - name: Upload reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: ./target/surefire-reports

  deploy:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Release Maven package
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} mvn -P release -B deploy -DskipTests -s settings.xml

